
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 15 20:38:05 BRT 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Caractere = 45;
  public static final int multiplicacao = 36;
  public static final int escreva = 17;
  public static final int divisao = 37;
  public static final int atribuicao = 25;
  public static final int programa = 8;
  public static final int Inteiro = 42;
  public static final int Real = 43;
  public static final int pv = 3;
  public static final int inteiro = 9;
  public static final int entao = 30;
  public static final int escrevaln = 18;
  public static final int bibIO = 2;
  public static final int de = 22;
  public static final int real = 10;
  public static final int faca = 24;
  public static final int Booleano = 32;
  public static final int leia = 19;
  public static final int abre_parenteses = 47;
  public static final int pf = 7;
  public static final int operador_logico = 39;
  public static final int dois_pontos = 13;
  public static final int fecha_parenteses = 48;
  public static final int se = 28;
  public static final int senao = 29;
  public static final int operadores_relacionais = 41;
  public static final int var = 12;
  public static final int EOF = 0;
  public static final int funcao = 15;
  public static final int enquanto = 27;
  public static final int para = 21;
  public static final int error = 1;
  public static final int leialn = 20;
  public static final int procedimento = 16;
  public static final int subtracao = 34;
  public static final int ERROR = 50;
  public static final int Palavra = 44;
  public static final int caractere = 46;
  public static final int id = 49;
  public static final int potencia = 35;
  public static final int palavra = 26;
  public static final int utilize = 4;
  public static final int negacao = 40;
  public static final int virgula = 14;
  public static final int soma = 33;
  public static final int fim = 6;
  public static final int booleano = 31;
  public static final int ini = 5;
  public static final int ate = 23;
  public static final int constante = 11;
  public static final int resto = 38;
}

